[package]
name = "rc"
version = "1.0.0"
edition = "2021"

[workspace]
members = ["crates/refer", "crates/refer-cli"]

[dependencies]
refer = { path = "./crates/refer", version = "0.1.3" }
refer-cli = { path = "./crates/refer-cli", version = "1.0.0" }

[[bin]]
name = "rc"
path = "src/main.rs"
