[package]
name = "refer-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
home = "0.5.5"
inquire = { version = "0.6.1", features = ["editor"] }
pico-args = "0.5.0"
refer = { path = "../refer" }
toml = "0.7.4"